# Generated by Django 5.0.4 on 2024-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smaartpro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("groupid", models.IntegerField(default=0)),
                ("list_type", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="feesreceipt",
            name="is_family",
            field=models.BooleanField(default=False),
        ),
    ]
