# Generated by Django 3.2.20 on 2024-07-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smaartpro', '0002_datalist_feesreceipt_is_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('groupid', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='list_type',
        ),
        migrations.AddField(
            model_name='datalist',
            name='type',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='feesreceipt',
            name='type',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='feesreceipt',
            name='receipt_type',
            field=models.IntegerField(choices=[(1, 'ORDINAIRE'), (2, 'CAISSE')], default=1),
        ),
    ]
