# Generated by Django 5.0.4 on 2024-10-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smaartpro", "0012_certificat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentcard",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="avispaiement",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="certificat",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="closecash",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="datalist",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="feesreceipt",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ficheagent",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ficheeleve",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ficheteacher",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recucaisse",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentcard",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="type",
            field=models.IntegerField(default=0),
        ),
    ]
