# Generated by Django 5.0.4 on 2024-10-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smaartpro", "0013_alter_agentcard_type_alter_avispaiement_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleveNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("groupid", models.IntegerField(default=0)),
                ("type", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
